version: '3.8'

services:
  app:
    build: 
      context: .
      target: ${BUILD_TARGET:-production}  # development o production
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fakpidb
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=3000
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      db:
        condition: service_healthy
    command: >
       sh -c "
        until npx prisma migrate deploy; do
        echo 'ğŸ• Esperando a que la base de datos estÃ© lista...';
        sleep 2;
        done;
        
        if [ \"$NODE_ENV\" = \"development\" ]; then
          echo 'ğŸš€ MODO DESARROLLO: Hot reload activado';
          npx prisma generate;
          npm run start:dev;
        else
          echo 'ğŸš€ MODO PRODUCCIÃ“N';
          node dist/main;
        fi
        "
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fakpidb
    ports:
      - "${DB_PORT:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fakpidb"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data: